//
//  GamesSelectionInteractor.swift
//  Sudoku
//
//  Created by Jovanco Jovanovski on 6/4/18.
//  Copyright (c) 2018 Jovanco Jovanovski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GamesSelectionBusinessLogic
{
  func doSomething(request: GamesSelection.Something.Request)
}

protocol GamesSelectionDataStore
{
  //var name: String { get set }
}

class GamesSelectionInteractor: GamesSelectionBusinessLogic, GamesSelectionDataStore
{
  var presenter: GamesSelectionPresentationLogic?
  var worker: GamesSelectionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: GamesSelection.Something.Request)
  {
    worker = GamesSelectionWorker()
    worker?.doSomeWork()
    
    let response = GamesSelection.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
