//
//  SudokuPresenter.swift
//  Sudoku
//
//  Created by Jovanco Jovanovski on 6/4/18.
//  Copyright (c) 2018 Jovanco Jovanovski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SudokuPresentationLogic
{
  func presentSomething(response: Sudoku.Something.Response)
}

class SudokuPresenter: SudokuPresentationLogic
{
  weak var viewController: SudokuDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Sudoku.Something.Response)
  {
    let viewModel = Sudoku.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
