//
//  SudokuInteractor.swift
//  Sudoku
//
//  Created by Jovanco Jovanovski on 6/4/18.
//  Copyright (c) 2018 Jovanco Jovanovski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SudokuBusinessLogic
{
  func doSomething(request: Sudoku.Something.Request)
}

protocol SudokuDataStore
{
  //var name: String { get set }
}

class SudokuInteractor: SudokuBusinessLogic, SudokuDataStore
{
  var presenter: SudokuPresentationLogic?
  var worker: SudokuWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Sudoku.Something.Request)
  {
    worker = SudokuWorker()
    worker?.doSomeWork()
    
    let response = Sudoku.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
